version: "3"
services:
  api:
    build: .
    ports:
      - 8080:8080
    image: api-dev
    volumes:
      - .:/go/src/api
    depends_on:
      - db
    environment: 
      DB_HOST: db
      DB_USER: bank_service
      DB_PASSWORD: yQGKSuS8tC
      DB_PORT: 5432
      DB_NAME: bank_service
      DB_SSLMODE: disable
    networks:
      - backend

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: yQGKSuS8tC
      POSTGRES_USER: bank_service
      POSTGRES_DB: bank_service
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-data:
networks:
  backend:
