version: "3"
services:
  api:
    build: .
    ports:
      - 8080:8080
    image: api-dev
    volumes:
      - .:/go/src/api
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: yQGKSuS8tC
      POSTGRES_USER: bank_service
      POSTGRES_DB: bank_service
      