version: "3"
services:
  api:
    build: .
    ports:
      - 8080:8080
    image: api-dev
    volumes:
      - ./:/go/src/github.com/nelsonmhjr/bank_service
    depends_on:
      - db
    environment: 
      DB_HOST: db
      DB_USER: bank_service
      DB_PASSWORD: yQGKSuS8tC
      DB_PORT: 5432
      DB_NAME_PREFIX: bank_service
      DB_SSLMODE: disable
      GIN_MODE: debug
    networks:
      - backend

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: yQGKSuS8tC
      POSTGRES_USER: bank_service
      POSTGRES_MULTIPLE_DATABASES: bank_service_development,bank_service_test
    ports:
      - 5432:5432
    volumes:
      - ./setup/postgres_init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-data:
networks:
  backend:
